// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI-powered symbolic analysis for personal and brand identities.
 *
 * - analyzeSymbolism - A function that takes text input and returns an analysis of its symbolic meanings and resonance.
 * - AnalyzeSymbolismInput - The input type for the analyzeSymbolism function.
 * - AnalyzeSymbolismOutput - The return type for the analyzeSymbolism function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeSymbolismInputSchema = z.object({
  text: z
    .string()
    .describe(
      'Text related to a personal or brand identity that needs symbolic analysis.'
    ),
});
export type AnalyzeSymbolismInput = z.infer<typeof AnalyzeSymbolismInputSchema>;

const AnalyzeSymbolismOutputSchema = z.object({
  analysis: z.string().describe('AI-powered analysis of the symbolic meanings and resonance of the input text.'),
});
export type AnalyzeSymbolismOutput = z.infer<typeof AnalyzeSymbolismOutputSchema>;

export async function analyzeSymbolism(input: AnalyzeSymbolismInput): Promise<AnalyzeSymbolismOutput> {
  return analyzeSymbolismFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeSymbolismPrompt',
  input: {schema: AnalyzeSymbolismInputSchema},
  output: {schema: AnalyzeSymbolismOutputSchema},
  prompt: `You are an AI expert in symbolic analysis, semiotics, branding, and psychology. Analyze the following text and provide a deep, insightful, and actionable analysis of its symbolic meanings, archetypal resonance, and potential impact.

Your response should be structured, detailed, and engaging.

Text for Analysis:
{{{text}}}`,
});

const analyzeSymbolismFlow = ai.defineFlow(
  {
    name: 'analyzeSymbolismFlow',
    inputSchema: AnalyzeSymbolismInputSchema,
    outputSchema: AnalyzeSymbolismOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
